name: Test Module

on:
  push:
    branches:
      - $default-branch
      - develop
    paths:
      - './**'
      - '.github/workflows/unit_tests.yml'
  pull_request:
    branches:
      - $default-branch
      - develop
    paths:
      - './**'
      - '.github/workflows/unit_tests.yml'

jobs:
  test:
    strategy:
      matrix:
        go-version:
          - 1.18.x
          - 1.19.x
        platform:
          - ubuntu-latest
          - windows-latest
    runs-on: '${{ matrix.platform }}'
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '${{ matrix.go-version }}'

      - name: Test `Brelem`
        run: go test -v -race ./...
